<!DOCTYPE html>
  <!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
  <!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
  <!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
  <!--[if gt IE 8]><!-->
<html lang="en" class="no-js"> <!--<![endif]-->
  <head>
    <title>MJ Repo Services - Auto Repossession and Recovery</title>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0" />
    <meta name="title" content="MJ Repo Services - Auto Repossession and Recovery" />
    <meta name="language" content="English" />
    <meta name="copyright" content="MJ Repo Services" />

    <meta name="description" content="text" />
    <meta name="description" content="MJ Repo Services" />
    <meta name="description" content="MJ Repo Services - Auto Repossession and Recovery" />
    <meta name="description" content="MJ Repo Services provides vehicle repossession and recovery services for Philadelphia, New Jersey, and Delaware" />
    <meta name="description" content="MJ Repo Services provides towing and recovery services for Philadelphia, South Jersey, and Delaware" />
    
    <meta name="keywords" content="text" />
    <meta name="keywords" content="Auto Repossession, Auto Recovery, Automobile Recovery, Recreation Vehicle Recovery, ATV Recovery, RV Recovery, Truck Recovery, Recovery Specialist, Repossession Service, Philadelphia Repossession Company, Collateral Recovery, Tri-State Repossession, Repo man, Repossession Agent, Philadelphia Repossession Company, Automobile Repossession, Recreation Vehicle Repossession, ATV Repossession, RV Repossession, Truck Repossession, Tri-State Vehicle Recovery, Delaware Repossession, New Jersey Repossession, New Jersey Vehicle Recovery, Delaware Vehicle Recovery, South Jersey Repossession, South Jersey Vehicle Recovery" />
    <meta name="keywords" content="Philadelphia Repossession, New Jersey Repossession, Delaware Repossession, South Jersey Repossession, Philadelphia Towing and Recovery, New Jersey Towing and Recovery, Delaware Towing and Recovery. South Jersey Towing and Recovery, Auto Repossession, Truck Repossession, RV Repossession, Vehicle Repossession, Towing, Towing and Recovery, Auto Towing, Truck Towing, RV Towing, Vehicle Towing" />

    <meta name="language" content="English" />
    <meta name="copyright" content="MJ Repo Services" />
    <meta name="robots" content="ALL" />
    <meta name="robots" content="INDEX, FOLLOW" />
    <meta name="robots" content="selection" />
    <meta name="revisit-after" content="7 days" />
    <meta name="document-classification" content="Auto Repossession and Recovery" />
    <meta name="document-rating" content="General" />
    <meta name="document-state" content="Dynamic" />
    <meta name="Abstract" content="MJ Repo Services - Auto Repossession and Recovery." />

    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://www.mjreposervices.com" />
    <meta property="og:description" content="MJ Repo Services provides repossession and recovery services for the Philadelphia, New Jersey, and Delaware areas" />

    <link rel="shortcut icon" href="images/favicon.ico"  type="image/x-icon" />
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif|Ubuntu' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="js/flexslider/flexslider.css" />
    <link rel="stylesheet" href="css/basic-style.css">
    <link rel="stylesheet" href="css/custom.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/table.css">
    <link href='http://fonts.googleapis.com/css?family=Permanent+Marker|Open+Sans:300italic,400italic,600italic,700italic,800italic,400,600,700,800,300|Roboto:400,100,300,100italic,400italic,300italic,500italic,500,700,700italic,900,900italic|Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Sans+Mono' rel='stylesheet' type='text/css'>
    <link href="http://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" type="text/css">
    <!-- JS-->
    <script src="js/libs/modernizr-2.6.2.min.js"></script>
    <!-- end JS-->
  </head>

  <body id="home" class="home">
  <!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->

  <section id="page-header" class="clearfix">    
    <div class="wrapper" style="text-align: center">
    	<h1 class="title"><a href="index.php" style="color: initial">MJ Repo Services</a></h1>
      <h1 class="title tap_call" style="display: none"><a href="tel:267-938-8123" style="text-decoration: none; color: red; font-family: Montserrat, sans-serif, cursive; font-style: italic; font-weight: 900; font-size: 1.25em"><img src="images/tap-to-call.png" style="width: 230px"></a></h1>
      <a href="https://scheduler.cleardata.io/#!/calendar?a=u-hf0f6yZGAykisy-gIKiNWVWsyLqG4cmvKowNkhTjY&b=xv1" title="Repossession Scheduling | Cleardata"><img id="vin" src="https://s3-us-west-2.amazonaws.com/files.cleardata.io/media/bookAppBtn_orange.png" alt="Repossession Software from Cleardata"></a>
    </div>
  </section>

  <!-- header area -->
  <header class="wrapper clearfix">
      <div id="banner">        
        <!-- <div id="logo"><a href="index.html"><img src="images/truck_6.png" alt="Elite Basement Solutions Logo" style="width:230px; border-radius: 5px; box-shadow: 7px 7px 15px #000"></a></div> -->
      </div>
      <!-- main navigation -->
      <nav id="topnav" role="navigation">
      <div class="menu-toggle">Menu</div>  
        <ul class="srt-menu" id="menu-main-navigation">
          <li><a href="services.php">Services</a></li>
          <li><a href="coverage.php" class="selected">Coverage Area</a></li>
          <li><a href="insurance.php">Insurance</a></li>
          <li><a href="about.php">About Us</a></li>
          <li><a href="contact.php">Contact Us</a></li>  
        </ul>     
      </nav><!-- #topnav -->
  </header><!-- end header -->

  <!-- main content area -->   
  <div class="wrapper" id="main">  
  <!-- content area -->    
    <section id="content">
        <div class="service_holder">
          <img class="service_truck" src="images/map1.gif" width="450px" style="margin: 25px 0 5px 0" alt="Map of MJ Repo Services coverage area - PA, NJ, DE">
        </div>
      <div class="pa">
        Pennsylvania
      </div>
      <table id="pa_coverage">
        <thead>
          <tr>
            <th>ZIP</th>
            <th>Town</th>
            <th>County</th>
          </tr>
        </thead>
        <tbody>
          <!-- BUCKS COUNTY -->
          <tr>
            <td>18039</td>
            <td>Durham</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18077</td>
            <td>Riegelsville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18081</td>
            <td>Springtown</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18901</td>
            <td>Doylestown</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18902</td>
            <td>Doylestown</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18910</td>
            <td>Bedminster</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18911</td>
            <td>Blooming Glen</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18913</td>
            <td>Carversville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18914</td>
            <td>Chalfont</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18916</td>
            <td>Danboro</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18917</td>
            <td>Dublin</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18917</td>
            <td>Dublin</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18920</td>
            <td>Erwinna</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18921</td>
            <td>Ferndale</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18922</td>
            <td>Forest Grove</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18923</td>
            <td>Fountainville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18925</td>
            <td>Furlong</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18926</td>
            <td>Gardenville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18928</td>
            <td>Holicong</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18929</td>
            <td>Jamison</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18930</td>
            <td>Kintnersville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18931</td>
            <td>Lahaska</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18933</td>
            <td>Lumverville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18934</td>
            <td>Mechanicsville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18935</td>
            <td>Milford Square</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18938</td>
            <td>New Hope</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18940</td>
            <td>Newtown</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18942</td>
            <td>Ottsville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18943</td>
            <td>Penns Park</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18944</td>
            <td>Perkasie</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18946</td>
            <td>Pineville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18947</td>
            <td>Pipersville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18949</td>
            <td>Plumsteadville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18950</td>
            <td>Point Pleasant</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18951</td>
            <td>Quakertown</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18953</td>
            <td>Revere</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18954</td>
            <td>Richboro</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18955</td>
            <td>Richlandtown</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18956</td>
            <td>Rushland</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18960</td>
            <td>Sellersville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18962</td>
            <td>Silverdale</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18963</td>
            <td>Solebury</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18966</td>
            <td>Holland</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18966</td>
            <td>Southampton</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18968</td>
            <td>Spinnerstown</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18970</td>
            <td>Trumbauersville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18972</td>
            <td>Upper Black Eddy</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18974</td>
            <td>Warminster</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18976</td>
            <td>Warrington</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18977</td>
            <td>Washington Crossing</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18980</td>
            <td>Wycomebe</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>18981</td>
            <td>Zionhill</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19007</td>
            <td>Tullytown</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19007</td>
            <td>Tullytown</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19020</td>
            <td>Andalusia</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19020</td>
            <td>Bensalem</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19021</td>
            <td>Croydon</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19030</td>
            <td>Fairless Hills</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19047</td>
            <td>Langhorne</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19047</td>
            <td>Penndel</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19053</td>
            <td>Upper Holland</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19053</td>
            <td>Feasterville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19053</td>
            <td>Trevose</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19053</td>
            <td>Langhorne</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19054</td>
            <td>Fallsington</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19056</td>
            <td>Levittown</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19056</td>
            <td>Newportville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19057</td>
            <td>Levittown</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19067</td>
            <td>Morrisville</td>
            <td>Bucks</td>
          </tr>
          <tr>
            <td>19067</td>
            <td>Yardley</td>
            <td>Bucks</td>
          </tr>

          <!-- CHESTER COUNTY -->
          <tr>
            <td>19031</td>
            <td>Paoli</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19310</td>
            <td>Atglen</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19311</td>
            <td>Avondale</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19312</td>
            <td>Berwyn</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19316</td>
            <td>Brandamore</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19318</td>
            <td>Chatham</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19320</td>
            <td>Coatesville</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19330</td>
            <td>Cochranville</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19333</td>
            <td>Devon</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19335</td>
            <td>Downingtown</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19341</td>
            <td>Exton</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19343</td>
            <td>Glenmoore</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19344</td>
            <td>Honey Brook</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19345</td>
            <td>Immaculata</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19346</td>
            <td>Kelton</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19347</td>
            <td>Kemblesville</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19348</td>
            <td>Kennett Square</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19350</td>
            <td>Landenberg</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19351</td>
            <td>Lewisville</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19353</td>
            <td>Lionville</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19355</td>
            <td>Malvern</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19355</td>
            <td>Frazer</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19357</td>
            <td>Mendenhall</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19360</td>
            <td>New London</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19362</td>
            <td>Nottingham</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19363</td>
            <td>Oxford</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19365</td>
            <td>Parkesburg</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19367</td>
            <td>Pomeroy</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19369</td>
            <td>Sadsburyville</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19370</td>
            <td>Steelville</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19372</td>
            <td>Thorndale</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19375</td>
            <td>Unionville</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19376</td>
            <td>Wagontown</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19380</td>
            <td>West Chester</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19381</td>
            <td>West Chester</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19382</td>
            <td>West Chester</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19390</td>
            <td>West Grove</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19395</td>
            <td>Westtown</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19397</td>
            <td>Southeastern</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19421</td>
            <td>Birchrunville</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19425</td>
            <td>Chester Springs</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19432</td>
            <td>Devault</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19442</td>
            <td>Kimberton</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19457</td>
            <td>Parker Ford</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19460</td>
            <td>Phoenixville</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19465</td>
            <td>Pottstown</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19470</td>
            <td>St. Petersburg</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19475</td>
            <td>Spring City</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19480</td>
            <td>Uwchland</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19481</td>
            <td>Valley Forge</td>
            <td>Chester</td>
          </tr>
          <tr>
            <td>19520</td>
            <td>Elverson</td>
            <td>Chester</td>
          </tr>
          
          <!-- DELAWARE COUNTY -->
          <tr>
            <td>19008</td>
            <td>Broomall</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19010</td>
            <td>Bryn Mawr</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19013</td>
            <td>Chester</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19013</td>
            <td>Eddystone</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19014</td>
            <td>Aston</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19014</td>
            <td>Chester</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19015</td>
            <td>Brookhaven</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19015</td>
            <td>Chester</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19016</td>
            <td>Chester</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19017</td>
            <td>Chester Heights</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19018</td>
            <td>Aldan</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19018</td>
            <td>Secane</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19018</td>
            <td>Clifton Heights</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19022</td>
            <td>Crum Lynne</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19022</td>
            <td>Chester</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19022</td>
            <td>Eddystone</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19023</td>
            <td>Collingdale</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19023</td>
            <td>Darby</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19026</td>
            <td>Pilgrim Gardens</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19026</td>
            <td>Drexel Hill</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19028</td>
            <td>Edgemont</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19029</td>
            <td>Lester</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19029</td>
            <td>Essington</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19032</td>
            <td>Folcroft</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19033</td>
            <td>Folsom</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19036</td>
            <td>Glenolden</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19037</td>
            <td>Glen Riddle</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19037</td>
            <td>Lima</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19039</td>
            <td>Gradyville</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19043</td>
            <td>Holmes</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19050</td>
            <td>Lansdowne</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19050</td>
            <td>Yeadon</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19052</td>
            <td>Lenni</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19061</td>
            <td>Boothwyn</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19061</td>
            <td>Linden</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19061</td>
            <td>Marcus Hook</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19061</td>
            <td>Trainer</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19063</td>
            <td>Elwyn</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19063</td>
            <td>Media</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19064</td>
            <td>Springfield</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19073</td>
            <td>Newtown Square</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19074</td>
            <td>Norwood</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19076</td>
            <td>Prospect Park</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19078</td>
            <td>Ridley Park</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19079</td>
            <td>Sharon Hill</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19081</td>
            <td>Swarthmore</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19082</td>
            <td>Upper Darby</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19083</td>
            <td>Havertown</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19085</td>
            <td>Villanova</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19086</td>
            <td>Wallingford</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19086</td>
            <td>Rose Valley</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19087</td>
            <td>Chesterbrook</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19087</td>
            <td>St. David</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19087</td>
            <td>Radnor</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19087</td>
            <td>Wayne</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19094</td>
            <td>Woodlyn</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19113</td>
            <td>Philadelphia</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19317</td>
            <td>Chadds Ford</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19319</td>
            <td>Cheyney</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19331</td>
            <td>Concordville</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19342</td>
            <td>Glen Mills</td>
            <td>Delaware</td>
          </tr>
          <tr>
            <td>19373</td>
            <td>Thornton</td>
            <td>Delaware</td>
          </tr>

          <!-- MONTGOMERY COUNTY -->
          <tr>
            <td>18041</td>
            <td>East Greenville</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18054</td>
            <td>Green Lane</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18070</td>
            <td>Palm</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18073</td>
            <td>Red Hill</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18074</td>
            <td>Perkiomenville</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18076</td>
            <td>Red Hill</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18084</td>
            <td>Sumneytown</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18915</td>
            <td>Colmar</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18918</td>
            <td>Earlington</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18924</td>
            <td>Franconia</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18936</td>
            <td>Montgomeryville</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18957</td>
            <td>Salford</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18958</td>
            <td>Salfordville</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18964</td>
            <td>Souderton</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18969</td>
            <td>Telford</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18971</td>
            <td>Tylersport</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>18979</td>
            <td>Woxall</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19001</td>
            <td>Abington</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19001</td>
            <td>Roslyn</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19002</td>
            <td>Ambler</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19002</td>
            <td>Lower Gwynedd</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19003</td>
            <td>Ardmore</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19004</td>
            <td>Belmont Hills</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19004</td>
            <td>Bala Cynwyd</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19006</td>
            <td>Huntingdon Valley</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19009</td>
            <td>Bryn Athyn</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19012</td>
            <td>Cheltenham</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19025</td>
            <td>Dresher</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19027</td>
            <td>Lamott</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19027</td>
            <td>Melrose Park</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19027</td>
            <td>Elkins Park</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19031</td>
            <td>Flourtown</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19034</td>
            <td>Fort Washington</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19035</td>
            <td>Gladwynne</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19038</td>
            <td>Erdenheim</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19038</td>
            <td>Wyndmoor</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19038</td>
            <td>Glenside</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19038</td>
            <td>Laverock</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19040</td>
            <td>Hatboro</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19041</td>
            <td>Haverford</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19044</td>
            <td>Horsham</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19046</td>
            <td>Meadowbrook</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19046</td>
            <td>Jenkintown</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19046</td>
            <td>Rydal</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19046</td>
            <td>Rockledge</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19066</td>
            <td>Merion Station</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19072</td>
            <td>Narberth</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19072</td>
            <td>Penn Valley</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19075</td>
            <td>Oreland</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19090</td>
            <td>Willow Grove</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19095</td>
            <td>Wyncote</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19096</td>
            <td>Wynnewood</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19401</td>
            <td>Norristown</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19041</td>
            <td>E. Norriton</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19403</td>
            <td>Audubon</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19403</td>
            <td>Eagleville</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19403</td>
            <td>Jeffersonville</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19403</td>
            <td>Norristown</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19405</td>
            <td>Bridgeport</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19405</td>
            <td>Norristown</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19406</td>
            <td>King Of Prussia</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19409</td>
            <td>Fairview Village</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19420</td>
            <td>Arcola</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19422</td>
            <td>Center Square</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19422</td>
            <td>Penllyn</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19422</td>
            <td>Blue Bell</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19423</td>
            <td>Cedars</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19426</td>
            <td>Collegeville</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19428</td>
            <td>Conshohocken</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19430</td>
            <td>Creamery</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19435</td>
            <td>Frederick</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19436</td>
            <td>Gwynedd</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19437</td>
            <td>Gwynedd Valley</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19438</td>
            <td>Harleysville</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19440</td>
            <td>Hatfield</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19443</td>
            <td>Kukpsville</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19444</td>
            <td>Lafayette Hill</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19446</td>
            <td>Lansdale</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19450</td>
            <td>Lederach</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19451</td>
            <td>Mainland</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19452</td>
            <td>Miquon</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19453</td>
            <td>Mont Clare</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19454</td>
            <td>North Wales</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19456</td>
            <td>Oaks</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19462</td>
            <td>Plymouth Meeting</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19464</td>
            <td>Sanatoga</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19464</td>
            <td>Pottstown</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19464</td>
            <td>Stowe</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19468</td>
            <td>Linfield</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19468</td>
            <td>Limerick</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19468</td>
            <td>Royersford</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19472</td>
            <td>Sassamansville</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19473</td>
            <td>Schwenksville</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19474</td>
            <td>Skippack</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19477</td>
            <td>Spring House</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19478</td>
            <td>Spring Mount</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19484</td>
            <td>Valley Forge</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19486</td>
            <td>West Point</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19490</td>
            <td>Worcester</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19492</td>
            <td>Zieglersville</td>
            <td>Montgomery</td>
          </tr>
          <tr>
            <td>19525</td>
            <td>Gilbertsville</td>
            <td>Montgomery</td>
          </tr>

          <!-- PHILADELPHIA COUNTY -->
          <tr>
            <td>19102</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19103</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19104</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19106</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19107</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19109</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19111</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19112</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19114</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19115</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19116</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19118</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19119</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19120</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19121</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19122</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19123</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19124</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19125</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19126</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19127</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19128</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19129</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19130</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19131</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19132</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19133</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19134</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19135</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19136</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19137</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19138</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19139</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19140</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19141</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19142</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19143</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19144</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19145</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19146</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19147</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19148</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19149</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19150</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19151</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19152</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19153</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
          <tr>
            <td>19154</td>
            <td>Philadelphia</td>
            <td>Philadelphia</td>
          </tr>
        </tbody>
      </table>
        <div class="service_holder">
          <img class="service_truck" src="images/map.png" width="350px" style="margin: 25px 0 0 0" alt="Map of MJ Repo Services coverage area - PA, NJ, DE">
        </div>
      <div class="nj">
        New Jersey
      </div>
      <table id="nj_coverage">
      <!-- MERCER COUNTY -->
          <thead>
            <th>ZIP</th>
            <th>Town</th>
            <th>County</th>
          </thead>
          <tbody>
            <tr>
              <td>08520</td>
              <td>East Windsor</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08560</td>
              <td>Ewing</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08618</td>
              <td>Ewing</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08628</td>
              <td>Ewing</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08638</td>
              <td>Ewing</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08620</td>
              <td>Groveville</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08609</td>
              <td>Hamilton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08610</td>
              <td>Hamilton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08619</td>
              <td>Hamilton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08620</td>
              <td>Hamilton Township</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08690</td>
              <td>Hamilton Square</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08520</td>
              <td>Hightstown</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08525</td>
              <td>Hopewell</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08648</td>
              <td>Lawrence</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08648</td>
              <td>Lawrenceville</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08619</td>
              <td>Mercerville</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08534</td>
              <td>Pennington</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08540</td>
              <td>Princeton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08550</td>
              <td>Princeton Junction</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08691</td>
              <td>Robbinsville</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08560</td>
              <td>Titusville</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08610</td>
              <td>Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08619</td>
              <td>Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08602</td>
              <td>Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08603</td>
              <td>Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08604</td>
              <td>Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08605</td>
              <td>Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08606</td>
              <td>Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08607</td>
              <td>Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08608</td>
              <td>Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08609</td>
              <td>Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08610</td>
              <td>Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08690</td>
              <td>Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08628</td>
              <td>West Trenton</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08550</td>
              <td>West Windsor</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08651</td>
              <td>Windsor</td>
              <td>Mercer</td>
            </tr>
            <tr>
              <td>08620</td>
              <td>Yardville</td>
              <td>Mercer</td>
            </tr>

            <!-- BURLINGTON COUNTY -->
            <tr>
              <td>08010</td>
              <td>Beverly</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08010</td>
              <td>Edgewater Park</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08011</td>
              <td>Birmingham</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08015</td>
              <td>Browns Mills</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08016</td>
              <td>Burlington</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08019</td>
              <td>Chatsworth</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08022</td>
              <td>Columbus</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08041</td>
              <td>Jobstown</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08042</td>
              <td>Juliustown</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08046</td>
              <td>Willingboro</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08048</td>
              <td>Lumberton</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08052</td>
              <td>Maple Shade</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08053</td>
              <td>Evesboro</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08053</td>
              <td>Evesham</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08053</td>
              <td>Marlton</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08054</td>
              <td>Mount Laurel</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08055</td>
              <td>Medford</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08055</td>
              <td>Medford Lakes</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08057</td>
              <td>Lenola</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08060</td>
              <td>Westampton</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08064</td>
              <td>New Lisbon</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08065</td>
              <td>Palmyra</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08068</td>
              <td>Pemberton</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08073</td>
              <td>Rancocas</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08075</td>
              <td>Delran</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08075</td>
              <td>Riverside</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08076</td>
              <td>Riverton</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08077</td>
              <td>Cinnaminson</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08088</td>
              <td>Shamong</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08088</td>
              <td>Tabernacle</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08088</td>
              <td>Vincentown</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08224</td>
              <td>New Gretna</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08505</td>
              <td>Bordentown</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08505</td>
              <td>Fieldsboro</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08511</td>
              <td>Cookstown</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08515</td>
              <td>Chesterfield</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08515</td>
              <td>Crosswicks</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08518</td>
              <td>Florence</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08554</td>
              <td>Roebling</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08562</td>
              <td>Jacobstown</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08562</td>
              <td>North Hanover</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08562</td>
              <td>Wrightstown</td>
              <td>Burlington</td>
            </tr>
            <tr>
              <td>08640</td>
              <td>Fort Dix</td>
              <td>Burlington</td>
            </tr>

            <!-- CAMDEN COUNTY -->
            <tr>
              <td>08009</td>
              <td>Albion</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08034</td>
              <td>Ashland</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08004</td>
              <td>Atco</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08106</td>
              <td>Audubon</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08007</td>
              <td>Barrington</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08031</td>
              <td>Bellmawr</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08009</td>
              <td>Berlin</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08091</td>
              <td>Berlin Township</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08012</td>
              <td>Blackwood</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08012</td>
              <td>Blenheim</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08030</td>
              <td>Brooklawn</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08101</td>
              <td>Camden</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08102</td>
              <td>Camden</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08103</td>
              <td>Camden</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08104</td>
              <td>Camden</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08105</td>
              <td>Camden</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08106</td>
              <td>Camden</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08107</td>
              <td>Camden</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08108</td>
              <td>Camden</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08109</td>
              <td>Camden</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08110</td>
              <td>Camden</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08018</td>
              <td>Cedar Brook</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08002</td>
              <td>Cherry Hill</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08003</td>
              <td>Cherry Hill</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08034</td>
              <td>Cherry Hill</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08089</td>
              <td>Chesilhurst</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08012</td>
              <td>Chews Landing</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08021</td>
              <td>Clementon</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08107</td>
              <td>Collingswood</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08108</td>
              <td>Collingswood</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08110</td>
              <td>Delair</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08009</td>
              <td>East Berlin</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08033</td>
              <td>Haddonfield</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08043</td>
              <td>Echelon</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08081</td>
              <td>Erial</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08026</td>
              <td>Gibbsboro</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08029</td>
              <td>Glendora</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08030</td>
              <td>Gloucester</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08031</td>
              <td>Gloucester City</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08035</td>
              <td>Haddon Heights</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08104</td>
              <td>Haddon Township</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08107</td>
              <td>Haddon Township</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08108</td>
              <td>Haddon Township</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08033</td>
              <td>Haddonfield</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08043</td>
              <td>Voorhees</td>
              <td>Camden</td>
            </tr>
              <td>08021</td>
              <td>Laurel Springs</td>
              <td>Camden</td>
            <tr>
              <td>08021</td>
              <td>Lindenwold</td>
              <td>Camden</td>
            </tr>
              <td>08049</td>
              <td>Magnolia</td>
              <td>Camden</td>
            <tr>
              <td>08109</td>
              <td>Merchantville</td>
              <td>Camden</td>
            </tr>
              <td>08059</td>
              <td>Mount Ephraim</td>
              <td>Camden</td>
            <tr>
              <td>08107</td>
              <td>Oaklyn</td>
              <td>Camden</td>
            </tr>
              <td>08109</td>
              <td>Pennsauken</td>
              <td>Camden</td>
            <tr>
              <td>08110</td>
              <td>Pennsauken</td>
              <td>Camden</td>
            </tr>
              <td>08021</td>
              <td>Pine Hill</td>
              <td>Camden</td>
            <tr>
              <td>08021</td>
              <td>Pine Valley</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08078</td>
              <td>Runnemede</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08081</td>
              <td>Sicklerville</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08083</td>
              <td>Somerdale</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08084</td>
              <td>Stratford</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08009</td>
              <td>Tansboro</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08033</td>
              <td>Tavistock</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08012</td>
              <td>Turnersville</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08089</td>
              <td>Waterford</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08108</td>
              <td>Westmont</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08095</td>
              <td>Winslow</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08003</td>
              <td>Woodcrest</td>
              <td>Camden</td>
            </tr>
            <tr>
              <td>08107</td>
              <td>Woodlynne</td>
              <td>Camden</td>
            </tr>

            <!-- GLOUCESTER COUNTY -->
            <tr>
              <td>08098</td>
              <td>Almonesson</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08085</td>
              <td>Auburn</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08028</td>
              <td>Aura</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08080</td>
              <td>Barnsboro</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08066</td>
              <td>Billingsport</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08096</td>
              <td>Blackwood</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08014</td>
              <td>Bridgeport</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08020</td>
              <td>Clarksboro</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08312</td>
              <td>Clayton</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08080</td>
              <td>Cross Keys</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08096</td>
              <td>Depotford</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08025</td>
              <td>Ewan</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08322</td>
              <td>Franklinville</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08027</td>
              <td>Gibbstown</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08028</td>
              <td>Glassboro</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08032</td>
              <td>Grenloch</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08062</td>
              <td>Harrison Township</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08039</td>
              <td>Harrisonville</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08096</td>
              <td>Jericho</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08085</td>
              <td>Logan</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08328</td>
              <td>Malaga</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08051</td>
              <td>Mantua</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08056</td>
              <td>Mickelton</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08061</td>
              <td>Mount Royal</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08062</td>
              <td>Mullica Hill</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08344</td>
              <td>Newfield</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08090</td>
              <td>Oak Valley</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08066</td>
              <td>Paulsboro</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08071</td>
              <td>Pitman</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08074</td>
              <td>Richwood</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08080</td>
              <td>Sewell</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08085</td>
              <td>Swedesboro</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08086</td>
              <td>Thorofare</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08090</td>
              <td>Wenonah</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08051</td>
              <td>West Deptford</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08063</td>
              <td>West Deptford</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08093</td>
              <td>Westville</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08094</td>
              <td>Williamstown</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08097</td>
              <td>Woodbury</td>
              <td>Gloucester</td>
            </tr>
            <tr>
              <td>08085</td>
              <td>Woolwich</td>
              <td>Gloucester</td>
            </tr>

            <!-- CUMBERLAND COUNTY -->
            <tr>
              <td>08349</td>
              <td>Bivalve</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08302</td>
              <td>Bridgeton</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08332</td>
              <td>Carmel</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08313</td>
              <td>Deerfield</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08314</td>
              <td>Delmont</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08315</td>
              <td>Dividing Creek</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08316</td>
              <td>Dorchester</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08360</td>
              <td>East Vineland</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08302</td>
              <td>Fairfield Township</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08320</td>
              <td>Fairton</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08321</td>
              <td>Fortescue</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08345</td>
              <td>Grandys Beach</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08323</td>
              <td>Greenwich Township</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08324</td>
              <td>Heislerville</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08332</td>
              <td>Laurel Lake</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08327</td>
              <td>Leesburg</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08329</td>
              <td>Mauricetown</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08332</td>
              <td>Millville</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08345</td>
              <td>Newport</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08348</td>
              <td>Port Elizabeth</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08352</td>
              <td>Rosenhayn</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08302</td>
              <td>Seabrook</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08353</td>
              <td>Shiloh</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08360</td>
              <td>South Vineland</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08302</td>
              <td>Stowe Creek Township</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08324</td>
              <td>Thompson Beach</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08302</td>
              <td>Upper Deerfield</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08360</td>
              <td>Vineland</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08361</td>
              <td>Vineland</td>
              <td>Cumberland</td>
            </tr>
            <tr>
              <td>08362</td>
              <td>Vineland</td>
              <td>Cumberland</td>
            </tr>

            <!-- SALEM COUNTY -->
            <tr>
              <td>08001</td>
              <td>Alloway</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08069</td>
              <td>Carneys Point</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08318</td>
              <td>Centerton</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08318</td>
              <td>Daretown</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08023</td>
              <td>Deepwater</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08318</td>
              <td>Elmer</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08038</td>
              <td>Hancocks Bridge</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08079</td>
              <td>Mannington</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08343</td>
              <td>Monroeville</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08347</td>
              <td>Norma</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08001</td>
              <td>Paradise Lakes</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08067</td>
              <td>Pedricktown</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08069</td>
              <td>Penns Grove</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08070</td>
              <td>Pennsville</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08098</td>
              <td>Pilesgrove</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08318</td>
              <td>Pittsgrove</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08072</td>
              <td>Quinton</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08079</td>
              <td>Salem</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08098</td>
              <td>Sharptown</td>
              <td>Salem</td>
            </tr>
            <tr>
              <td>08098</td>
              <td>Woodstown</td>
              <td>Salem</td>
            </tr>
          </tbody>
      </table>
        <div class="service_holder">
          <img class="service_truck" src="images/map2.png" width="450px" style="margin: 15px 0 0 0; background: #91AA9D" alt="Map of MJ Repo Services coverage area - PA, NJ, DE">
        </div>
      <div class="de">
        Delaware
      </div>
      <table id="de_coverage">
      <!-- NEW CASTLE COUNTY -->
          <thead>
            <th>ZIP</th>
            <th>Town</th>
            <th>County</th>
          </thead>
          <tbody>
            <tr>
              <td>19701</td>
              <td>Bear</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19702</td>
              <td>Newark</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19703</td>
              <td>Claymont</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19706</td>
              <td>Delaware City</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19707</td>
              <td>Hockessin</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19708</td>
              <td>Kirkwood</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19709</td>
              <td>Middletown</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19710</td>
              <td>Montchanin</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19711</td>
              <td>Newark</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19712</td>
              <td>Newark</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19713</td>
              <td>Newark</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19714</td>
              <td>Newark</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19715</td>
              <td>Newark</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19716</td>
              <td>Newark</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19717</td>
              <td>Newark</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19718</td>
              <td>Newark</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19720</td>
              <td>New Castle</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19721</td>
              <td>New Castle</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19725</td>
              <td>Newark</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19730</td>
              <td>Odessa</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19731</td>
              <td>Port Penn</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19732</td>
              <td>Rockland</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19733</td>
              <td>Saint Georges</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19734</td>
              <td>Townsend</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19736</td>
              <td>Yorklyn</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19801</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19802</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19803</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19804</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19805</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19806</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19807</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19808</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19809</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19810</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19850</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19880</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19884</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19885</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19886</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19890</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19891</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19892</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19893</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19894</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19895</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19896</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19897</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19898</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
            <tr>
              <td>19899</td>
              <td>Wilmington</td>
              <td>New Castle</td>
            </tr>
          </tbody>
      </table>
    </section><!-- #end content area -->
  </div><!-- #end div #main .wrapper -->

  <h1 class="title tap_call tap_call2" style="display: none"><a href="tel:267-938-8123" style="text-decoration: none; color: red; font-family: Montserrat, sans-serif, cursive; font-style: italic; font-weight: 900; font-size: 1.25em"><img src="images/tap-to-call.png" style="width: 250px"></a></h1>
  <!-- footer area -->    
 <footer style="text-align: center">
    <div id="colophon" class="clearfix">
      <div style="font-size: 2em; margin-bottom: 10px">Licensed - Insured - Bonded</div>
      <p style="text-align: center; font-size: 1.15em; font-weight: 600">License No. 48492</p>
    </div>
      <p style="text-align: center; font-size: 1.15em; font-weight: 600"><a href="mailto:mjrepo@comcast.net" style="text-decoration: none; color: #0B5B76; font-weight: 600">mjrepo@comcast.net</a></p>
<!--     <div id="social_media">
      <a href="#" target="_blank"><img class="google_icon" src="images/google_icon.png"></a>
    </div> -->

     <p style="text-align: center; margin-top: 15px; font-weight: 600">
      &copy; <?php echo date("Y") ?> - <a href="inex.php" style="text-decoration: none">MJ Repo Services</a>
    </p>
  </footer><!-- #end footer area --> 


  <!-- jQuery -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/libs/jquery-1.9.0.min.js">\x3C/script>')</script>
  <script defer src="js/flexslider/jquery.flexslider-min.js"></script>
  <!-- fire ups - read this file!  -->   
  <script src="js/main.js"></script>
  <script src="js/phone.js"></script>
  </body>
</html>
